Translation of Z-Data Array part
ZHaskell/docs-zh pull request #5
Opened 2021-04-16 08:15 UTC by wfnuser

翻译Z-Data文档

2021-04-16 09:28 UTC, winterland1989 commented on Z-Data/Array.md
> +我们很难直接使用这些函数，因为它们直接操作`State#`令牌，并且它们区分不同的数组类型：如封装类型(uboxed)的`Array#`，`ByteArray#`等。这些类型后的`#`表示它们是特殊的原始类型，我们将稍后将进行讨论。
boxed `Array#`, `ByteArray#` -> 盒装的 `Array#`, `ByteArray#`

统一下术语：
unboxed： 非盒装的
boxed：盒装的
unlifted：非提升的
lifted：提升的
 
也没其他太好的翻译，暂时按照这个标准执行吧

2021-04-16 10:09 UTC, wfnuser commented on Z-Data/Array.md
> +我们很难直接使用这些函数，因为它们直接操作`State#`令牌，并且它们区分不同的数组类型：如封装类型(uboxed)的`Array#`，`ByteArray#`等。这些类型后的`#`表示它们是特殊的原始类型，我们将稍后将进行讨论。
搞定
lifted的部分还没搞懂... 晚点翻...

2021-04-16 13:19 UTC, alissa-tung commented on Z-Data/Array.md
> +我们很难直接使用这些函数，因为它们直接操作`State#`令牌，并且它们区分不同的数组类型：如封装类型(uboxed)的`Array#`，`ByteArray#`等。这些类型后的`#`表示它们是特殊的原始类型，我们将稍后将进行讨论。
一会加到[这里](https://github.com/ZHaskell/docs-zh/blob/master/terminology.md)叭

2021-04-16 23:58 UTC, alissa-tung requested changes

2021-04-16 23:58 UTC, alissa-tung commented on Z-Data/Array.md
> +与普遍存在的链表类型`[a]`不同。在Haskell中，没有任何内置语法支持，或者任何其他特殊的编译器支持数组,除了一些内置的原生函数，可以在[ghc-prim](http://hackage.haskell.org/package /ghc-prim/docs/GHC-Prim.html)中找到
中英之间空格比较好？另外数组第一次出现的时候可以考虑 `数组（Array）`

2021-04-16 23:58 UTC, alissa-tung commented on Z-Data/Array.md
> +在haskell中，从C语言的角度来看几乎每个你所见到的的值都是一个指针，即指向堆对象的内存位置，例如，像这样的数据类型：
大小写先改掉，在上游有要写入的东西的时候一起 patch 掉

2021-04-16 23:58 UTC, alissa-tung commented on Z-Data/Array.md
> +在运行时，值`foo`是引用，且所有的操作，例如模式匹配，都需要进行引用求值(dereferencing)。这样的值称为*封装类型(boxed)*，因为它是对盒子的引用，即持有[info-table](https://gitlab.haskell.org/ghc/ghc/-/wikis/commentary/rts/storage/heap-objects#info-tables)的堆上对象。信
名词在第一次出现在括号中时考虑大写

2021-04-16 23:58 UTC, alissa-tung commented on Z-Data/Array.md
> +                                                      封装的数组大部分操作作用于数组元素时都是懒加载的
lazy 一般翻译为惰性

2021-04-16 23:58 UTC, alissa-tung commented on Z-Data/Array.md
> +为了可以更轻松地使用这些类型，我们提供了ADT包装器：
ADT 封装会好一些吗？idk

2021-04-17 00:01 UTC, alissa-tung commented on Z-Data/Array.md
> +与普遍存在的链表类型`[a]`不同。在Haskell中，没有任何内置语法支持，或者任何其他特殊的编译器支持数组,除了一些内置的原生函数，可以在[ghc-prim](http://hackage.haskell.org/package /ghc-prim/docs/GHC-Prim.html)中找到
原生一般说 natïve，primitive fns 要不要考虑原语函数或者仅原语？idk

2021-04-17 11:51 UTC, alissa-tung commented on Z-Data/Array.md
> +我们很难直接使用这些函数，因为它们直接操作`State#`令牌，并且它们区分不同的数组类型：如封装类型(uboxed)的`Array#`，`ByteArray#`等。这些类型后的`#`表示它们是特殊的原始类型，我们将稍后将进行讨论。
gonna add it in my next pr, so resolved

2021-04-19 01:46 UTC, wfnuser commented on Z-Data/Array.md
> +在haskell中，从C语言的角度来看几乎每个你所见到的的值都是一个指针，即指向堆对象的内存位置，例如，像这样的数据类型：
这个是说haskell改成Haskell嘛？

2021-04-19 01:49 UTC, wfnuser commented on Z-Data/Array.md
> +与普遍存在的链表类型`[a]`不同。在Haskell中，没有任何内置语法支持，或者任何其他特殊的编译器支持数组,除了一些内置的原生函数，可以在[ghc-prim](http://hackage.haskell.org/package /ghc-prim/docs/GHC-Prim.html)中找到
done

2021-04-19 06:38 UTC, winterland1989 approved these changes

2021-04-19 06:38 UTC, winterland1989 commented on Z-Data/Array.md
> +在其他语言中，你通常必须区分 *引用* 和 *值*。例如，在C中，指针是对其他对象的引用。从硬件的角度来看，指针是一个内存地址：你可以使用机器代码来表示它所指向的内存的引用。而其他非指针类型的值就不是一个内存地址了，它们的1-0排列表示了该类型的某个值。
use machine code to follow 这里 follow 翻译不准确

2021-04-19 06:48 UTC, wfnuser commented on Z-Data/Array.md
> +在其他语言中，你通常必须区分 *引用* 和 *值*。例如，在C中，指针是对其他对象的引用。从硬件的角度来看，指针是一个内存地址：你可以使用机器代码来表示它所指向的内存的引用。而其他非指针类型的值就不是一个内存地址了，它们的1-0排列表示了该类型的某个值。
done

2021-04-19 06:55 UTC, wfnuser commented on Z-Data/Array.md
> +在haskell中，从C语言的角度来看几乎每个你所见到的的值都是一个指针，即指向堆对象的内存位置，例如，像这样的数据类型：
done

2021-04-19 07:00 UTC, winterland1989 approved these changes

2021-04-19 07:00 UTC, merged